TransformerOptimus/SuperAGI

requirements.txt

when I did pip install -r requirements.txt
psycopg2 came as missing so I added it to requirements.txt

added missing dependency

---

superagi/tools/searx/README.MD
superagi/tools/searx/search_scraper.py
superagi/tools/searx/searx.py

[Searx](https://github.com/searx/searx) is a "free internet metasearch engine which aggregates results from more than 70 search services" [(from their docs)](https://searx.github.io/searx/). I added a simple beautifulsoup scraper that allows many of the instances on https://searx.space/ to be used without an API key. Uses the `bs4`, `httpx`, and `pydantic` packages which are already in the `requirements.txt`. Tested it and it works well, although maybe we should add an option to not output just the summary but also the snippets of raw search results.

Adds support for searx search

---

docker-compose.yaml

Use fully qualified image names instead of aliases to support using podman instead of docker.
By default podman does not support aliases for image names and fails to run SuperAGI using this compose file. In file `/etc/containers/registries.conf` from podman we can find this note:
```txt
```

docker-compose fix for podman

---

gui/pages/Content/Agents/AgentCreate.js
superagi/helper/token_counter.py

Adding support to Open AI latest ```gpt-3.5-turbo-16k```

gpt-3.5-turbo-16k support

---

README.MD

I spent ~20 minutes trying to follow the current instructions in the README - it doesn't seem to be possible to set up an API key for Google Custom Search JSON from the Google Console. This has to be done in a separate place.
https://github.com/TransformerOptimus/SuperAGI/issues/155
Link to the correct URL where an API key can be created:
https://developers.google.com/custom-search/v1/introduction

docs: update link to google custom search

---

superagi/models/agent_config.py
superagi/models/agent_execution.py
superagi/models/agent_execution_feed.py
superagi/models/agent_execution_permission.py
superagi/models/agent_template.py
superagi/models/agent_template_config.py
superagi/models/agent_workflow.py
superagi/models/agent_workflow_step.py
superagi/models/configuration.py
superagi/models/toolkit.py
superagi/tools/email/read_email.py
superagi/tools/email/send_email.py
superagi/tools/email/send_email_attachment.py
superagi/tools/file/append_file.py
superagi/tools/file/delete_file.py
superagi/tools/file/write_file.py
superagi/tools/github/add_file.py
superagi/tools/github/delete_file.py
superagi/tools/github/search_repo.py
superagi/tools/google_search/google_search.py
superagi/tools/google_serp_search/google_serp_search.py
superagi/tools/jira/edit_issue.py
superagi/tools/jira/get_projects.py
superagi/tools/jira/search_issues.py
superagi/tools/thinking/tools.py

Docs fixes in different tools and modiles

fixing docs for tools and models

---

gui/pages/_app.css

Resolved the dropdown visibility bug in safari by changing minor css globally
Issue #530 
Involved a minor css change in the global css file
Used different browsers

dropdown not working in safari bug fixed, FIX #530

---

gui/pages/Content/Agents/AgentTemplatesList.js
gui/pages/Content/Marketplace/Market.js
gui/pages/Dashboard/Content.js

Made marketplace to have persistent data, switching tab will not replace the marketplace tab data to tools screen
None
Used local storage to store the most recent changes to the marketplace tab
Open a marketplace tab, click on a template to open the template detail page and open some other tab, switching back to the marketplace place doesn't reset the tab to tools section as it did before

Local Storage to Marketplace

---

.gitignore
superagi/agent/super_agi.py
superagi/jobs/agent_executor.py

Solved endless loop and hanging UI by extending our error catching by expanding conditional check to properties.
Solved endless loop and hanging UI by extending our error catching.  We were getting an uncaught exception because response['content'} was throwing a KeyError when response does not contain a 'content' property.  
```
Traceback (most recent call last):
superagi-celery-1           |   File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 451, in trace_task
superagi-celery-1           |     R = retval = fun(*args, **kwargs)
superagi-celery-1           |   File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 734, in __protected_call__
superagi-celery-1           |     return self.run(*args, **kwargs)
superagi-celery-1           |   File …
```

Conditional statement expanded for errored API response (close #560)

---

superagi/controllers/agent.py

This is a bugfix for the API endpoint - get_agents_by_project_id in controllers>agents.py
The endpoint was throwing 500 internal server error.
- The issue appeared whenever there wasn't any agent under a specific project id
- The returning list was not initialized, hence it was throwing a 'reference before assignment' error.
Query the API for various project ids, specifically the ones having no active agents.

BugFix: Get_Agents_Project_id throwing 500 internal Server Error

---

superagi/controllers/agent.py
tests/unit_tests/controllers/test_agent.py

Minor Change in response for Agent Scheduling Endpoint
start_time and start_date was needed to be sent to frontend. So, I have added it to the /agents/get/schedule_data endpoint.

Minor Change in response for Agent Scheduling Endpoint

---

superagi/vector_store/qdrant.py
superagi/vector_store/vector_factory.py
tests/unit_tests/vector_store/test_vector_factory.py

Qdrant 2.0

---

superagi/agent/output_parser.py
superagi/agent/prompts/analyse_task.txt
superagi/agent/prompts/initialize_tasks.txt
superagi/agent/prompts/superagi.txt
superagi/agent/super_agi.py

Changing the JSON output to Json schema

moving json structure to json schema structure in agent

---

superagi/agent/output_parser.py
superagi/agent/super_agi.py
superagi/helper/json_cleaner.py
superagi/lib/logger.py
superagi/tools/code/write_code.py
superagi/tools/google_serp_search/google_serp_search.py
superagi/tools/jira/edit_issue.py
tests/unit_tests/agent/test_output_parser.py
tests/unit_tests/agent_permissions/test_check_permission_in_restricted_mode.py
tests/unit_tests/helper/test_json_cleaner.py

- Fixing json parsing for boolean values
- Minor code refactoring

Twitter tool fix

---

gui/pages/Content/APM/ApmDashboard.js
gui/pages/Content/Agents/AgentCreate.js
gui/pages/Content/Agents/ResourceList.js
gui/pages/Content/Marketplace/AgentTemplate.js
gui/pages/_app.css

Bugs Resource Manager

---

superagi/helper/resource_helper.py
superagi/resource_manager/file_manager.py
tests/unit_tests/helper/test_resource_helper.py

Fixed duplication of resource.
Improve of coder of supercoder saw duplicate resources made when the same file was overwritten.
Handled by add or update resource.

Resource duplicate fix

---

superagi/agent/output_parser.py
superagi/agent/super_agi.py
superagi/resource_manager/llama_document_summary.py
superagi/resource_manager/resource_manager.py
superagi/resource_manager/resource_summary.py

fix  TypeError in superagi.worker # summarize_resource 
Have added a check to make sure it is not None

document fix

---

gui/pages/Content/Agents/ActivityFeed.js
gui/pages/Content/Agents/AgentCreate.js
gui/pages/Content/Agents/AgentSchedule.js
gui/pages/Content/Agents/AgentTemplatesList.js
gui/pages/Content/Agents/AgentWorkspace.js
gui/pages/Dashboard/Content.js
gui/pages/Dashboard/Settings/Settings.js
gui/pages/_app.css
gui/utils/utils.js

Bugs fixes new

---

superagi/agent/super_agi.py
superagi/jobs/agent_executor.py

Handling the rate limit exception

---

.gitignore
entrypoint.sh
install_tool_dependencies.sh
main.py
superagi/controllers/toolkit.py
superagi/helper/tool_helper.py
superagi/jobs/agent_executor.py
superagi/tool_manager.py
tests/unit_tests/controllers/test_toolkit.py
tests/unit_tests/test_tool_manager.py

- Added support for marketplace tools from superagi-tools
- superagi-tools will be available as marketplace tools in both PROD and DEV mode
-  tools.json will have all tools of marketplace and installed external tool listed.
- On start up of application marketplace tools and external tools are installed.
- Added download of marketplace tools at the start of the application in the start up script.
- Installation of both marketplace and external tools in the start up.

External repo support for marketplace

---

gui/pages/Content/Knowledge/KnowledgeForm.js

Currently we support Open AI “text-knowledge-ada-002” model knowledge only. Please make sure you add the same. changed to Currently we support Open AI “text-embedding-ada-002” model knowledge only. Please make sure you add the same.

“text-knowledge-ada-002” to  “text-embedding-ada-002”

---

gui/pages/Content/Agents/Agents.js
gui/pages/Content/Agents/Agents.module.css
gui/pages/Content/Agents/ResourceList.js
gui/pages/Content/Agents/ResourceManager.js
gui/pages/Content/Knowledge/Knowledge.js
gui/pages/Content/Toolkits/Toolkits.js
gui/pages/Dashboard/Dashboard.module.css
gui/pages/Dashboard/TopBar.js
gui/pages/_app.css

Frontend refactor

---

superagi/controllers/agent.py
superagi/controllers/agent_execution.py
superagi/controllers/agent_execution_config.py
superagi/controllers/types/agent_execution_config.py
superagi/models/agent.py
superagi/models/agent_config.py

Changes in 6 files:
**controllers/agent.py** -> removed the fetch details api and i have moved it to the controllers/agent_execution_config.py file
and in the create_agent_with_config function i have added new agent_execution_configs
**models/agent_config.py** -> added a update_agent_configurations_table function which updates the "agent_configurations" table 
whenever we run edit agent
**controllers/agent_execution_config.py** -> added a new api call(get_agent_execution_configuration) , which is used by frontend to fetch the details of the execution/ run
**controllers/ agent_execution.py** -> added a new api call(create_agent_run), which is used to create a new execution/ run
**controllers/ type/ agent_execution_config.py** -> created this new file which contains the AgentRunIn class, …

Edit agent feature

---

superagi/tools/email/send_email.py
superagi/tools/email/send_email_attachment.py
tests/unit_tests/tools/email/test_send_email_attachment.py

Email attach fix

---

Dockerfile

Download nltk files in build step
Checked the running image and found that nltk downloads two files 'averaged_perceptron_tagger' and 'punkt'
so we are downloading and keeping these files in the build step itself

Download nltk files in build step

---

superagi/models/agent_config.py
tests/unit_tests/controllers/test_update_agent_config_table.py

Schedule Agent Fix

---

superagi/agent/tool_builder.py

External tools, marketplace tools fix

---

superagi/helper/s3_helper.py
superagi/tools/file/list_files.py
tests/unit_tests/helper/test_s3_helper.py

Fix for list file with S3 storage type
I have fixed the working of List File Tool in case of S3 storage type
Use List File Tool with S3 File type.

List File S3

---

gui/pages/Content/APM/ApmDashboard.js
gui/pages/Content/Toolkits/ToolkitWorkspace.js

fronted is not building because of syntax error
but seems to be working when ```npm run dev``` because the rules are more relaxed

frontend fixes

---

superagi/controllers/api/agent.py
superagi/worker.py

fixed the resume agent and update agent bug

fixed api_bug

---

superagi/controllers/toolkit.py
tests/unit_tests/controllers/test_toolkit.py

Toolmarketplace

---

Dockerfile
DockerfileCelery
requirements.txt
superagi/models/agent_execution_feed.py
superagi/resource_manager/file_manager.py
superagi/tools/file/prompts/add_images_to_html.txt
superagi/tools/file/prompts/content_to_html_prompt.txt
superagi/tools/file/write_file.py
superagi/tools/image_generation/stable_diffusion_image_gen.py
superagi/tools/tool_response_query_manager.py

Reverts TransformerOptimus/SuperAGI#928
Unit Test needs to be added.

Revert "PDF and DOCX support in Write File - Feature Improvement, close #548"

---

superagi/jobs/agent_executor.py

Stop agent if model doesnt exsist
If model does exsist it throws an exception
we use this exception to stop

stop agent from executing if model is not found

---

.do/app.yaml
.do/deploy.template.yaml
Dockerfile
DockerfileRedis
README.MD

Added deploy to digitalocean button. One click docker deployment

Docker digitalocean deployment

---

superagi/controllers/agent_execution.py
superagi/controllers/api/agent.py
superagi/jobs/scheduling_executor.py

Fix for None Type error - schedule agent

Fix for schedule agent

---

install_tool_dependencies.sh

Re-submitting this PR due to an accidental pollution of commits into our fork.  Wanted to make sure it was clean.  Apologies I don't mean to waste time.
I need the ability to add some additional libraries outside of python itself as I wanted to create a tool for running headless chrome.  That required a number of dependancies installed using the apt tool.  
NA
I duplicated what is done for pip installs and modified it for apt.
Include a file called /app/requirements_apt.txt, add the name of an apt package, monitor stack logs for successful installation of said package on docker compose up.

Added functionaility to use APT packages

---

README.MD
gui/pages/Content/Agents/AgentCreate.js
gui/pages/Content/Models/ModelInfo.js
install_tool_dependencies.sh
main.py
superagi/controllers/agent_execution.py
superagi/controllers/models_controller.py
superagi/jobs/scheduling_executor.py
superagi/models/models.py
superagi/tools/tool_response_query_manager.py
tools.json

Syncing Main to Dev before release v12.

Main to dev sync v12

---

main.py
requirements.txt
superagi/controllers/organisation.py
superagi/helper/github_helper.py
superagi/llms/llm_model_factory.py
superagi/resource_manager/llama_document_summary.py
superagi/tools/github/fetch_pull_request.py
superagi/tools/github/github_toolkit.py
superagi/tools/github/prompts/code_review.txt
superagi/tools/github/review_pull_request.py
tests/unit_tests/helper/test_github_helper.py
tests/unit_tests/llms/test_model_factory.py
tests/unit_tests/tools/github/test_fetch_pull_request.py
tests/unit_tests/tools/github/test_review_pull_request.py

Github fetch pull requests and review pull request tools

GitHub pull request tools

---

tests/unit_tests/tools/github/test_review_pull_request.py

Fixing Unit Test for review pull request

Unit Test Fix

---

gui/pages/Content/Models/MarketModels.js
gui/pages/Content/Models/ModelTemplate.js
superagi/controllers/models_controller.py
superagi/controllers/types/models_types.py
superagi/models/models.py
tests/unit_tests/controllers/test_models_controller.py

Added Models Type Enum file.
Added content for Marketplace and edited the css.
Previously Installed state is changed back to Install state

models marketplace changes

---

Dockerfile

This a very small change just removing python3-dev from the docker file.
This caused on conflict error with python:3.10-slim-bullseye when I attempted to run: docker compose up --build.
The base image python:3.10-slim-bullseye already contains the necessary Python development tools, making the explicit installation of python3-dev redundant and error-prone.
I found this issue whilst running "docker compose up --build" not "docker-compose up --build" so it may be related to the issues seen in issue #507

docker compose up --build : python3.9 conflict with python3.10 fix

---

superagi/helper/s3_helper.py
superagi/helper/validate_csv.py
superagi/tools/file/read_file.py

fixes for read tool and list tool

---

gui/pages/Content/Agents/ActivityFeed.js
gui/utils/utils.js
superagi/agent/agent_iteration_step_handler.py
superagi/worker.py

Maintaining dev

---

superagi/jobs/agent_executor.py

added logs

---

superagi/controllers/models_controller.py
superagi/models/models.py

Models Marketplace bug fix for dev

---

.github/workflows/ci.yml

cache ~/.cache/pip folder in workflows
Currently lint and test takes ~4 mins, but out of that ~3.20 mins is spent on only installing dependencies.
Using actions/cache@v2 to basically saves the ~/.cache/pip folder, with hash of requirments.txt as key.
if requirments.txt changes automatically hash will changes.

add cache layer

---

gui/pages/Content/Agents/AgentCreate.js
gui/pages/Content/Agents/AgentTemplatesList.js
gui/pages/Content/Agents/AgentWorkspace.js
gui/pages/Dashboard/Content.js

mixpanel changes

---

gui/package-lock.json
gui/package.json
gui/pages/Dashboard/TopBar.js
gui/pages/_app.js

adding cookie in access token

---

gui/pages/Content/Models/ModelForm.js

models error fixed

---

config_template.yaml
superagi/helper/encyption_helper.py

fix for #1373

---

superagi/llms/openai.py
tests/unit_tests/llms/test_open_ai.py

With these changes the agent won't stop if a ratelimit error or timeout error or try again error is hit from the openai library, it will try again. 
#1255 
The agent will attempt to wait 5 times with an exponential backoff strategy and try again, it will wait for a minimum of 30 seconds and max of 300 seconds.
If after 5 attempts the api call still fails it will return the error.
The code is tested by mocking the api calls to openai and having it return the errors mentioned above and checking if the function has called the api specified number of times and it returns the expected error as a dictionary object.
To reduce the time taken to test, the tencity library's wait_random_exponential function is mocked to only use 0.1 seconds

Openai error handling for ratelimit, timeout and try again errors(fix #1255)

---

superagi/controllers/user.py
superagi/helper/auth.py

To address the issue, we need to add detailed logging, validate the incoming request data, and return a detailed error message if the validation fails. This will help in capturing the incoming request data and ensuring all required fields are present and correctly formatted.
To resolve the issue with HTTP basic auth, we need to modify the `get_current_user` method to check for the presence of HTTP basic auth headers and validate them if present. If HTTP basic auth is used, extract the username from the Authorization header and use it to fetch the user from the database.

Supercoder Issue 1358 Resolved

---

superagi/controllers/resources.py

Our [ZeroPath.com](https://zeropath.com) code security tool has found a broken authentication flaw enabling us to view tens of thousands of customers' files (via the publically hosted version). It enabled us to access secrets, business documents, and health information belonging to other users. We have created a patch to enforce authorization when fetching a resource.
We created this PR because we were unable to find a maintainer or a relevant security contact.

Fix IDOR Security Vulnerability on /api/resources/get/{resource_id}
