test.py

Aditya raj singh1992 patch input

---

test.py

Reverts TransformerOptimus/SuperAGI#77

Revert "Aditya raj singh1992 patch input"

---

README.MD

updated contributors and added screenshots

Readme 22 05

---

requirements.txt
test.py

V0.0.3 Minor FIx

---

superagi/tools/email/README.MD

Fix typo in email/README.MD

---

README.MD

Readme updated

---

config_template.yaml

I'm an AI researcher, and this is My first open source contribution.

Minor spelling correction in config-template.yaml

---

superagi/tools/image_generation/dalle_image_gen.py
superagi/tools/image_generation/image_gen_test.py

Dalle image gen

---

.gitattributes
.vscode/settings.json

setting gitattribute to always have LF for files ending with sh

Set lf as default

---

README.MD

Fixed Readme

---

superagi/controllers/config.py

OpenAI key backward compatible fix handling from .yaml if not given in frontend

API backward compatible

---

superagi/controllers/organisation.py

Handling hardcoded organisation to retain agents.

code refactor

---

gui/pages/Content/Agents/AgentCreate.js
gui/pages/Dashboard/Content.js
gui/pages/Dashboard/TopBar.js
gui/pages/_app.js

not letting to create agents if api key is empty, forcefully opening the settings popup where user can enter api key there

OpenAi API key empty check

---

README.MD

Updated readme error on reddit link

Update readme to fix reddit link

---

superagi/jobs/agent_executor.py

Identified and resolved a small coding style inconsistency in the source code.

Fix Minor Coding Style Issue

---

gui/pages/_app.js
gui/utils/utils.js

Authorisation header was absent while downloading file from resource manager

Headers in download file

---

gui/pages/_app.js

Null orgid issue causing unprocessable entity issue

Null organisation id resolution

---

gui/pages/Content/Agents/AgentCreate.js
gui/pages/Content/Agents/Agents.module.css
gui/pages/Content/Agents/TaskQueue.js
gui/pages/Content/Tools/Tool.module.css
gui/pages/Content/Tools/Tools.js

Task queue headers styling, default cursor over tools in tools list, removed Human tool from frontend.

Frontend fixes

---

gui/pages/api/apiConfig.js
superagi/helper/resource_helper.py
superagi/helper/s3_helper.py
superagi/jobs/agent_executor.py
superagi/tools/file/write_file.py
superagi/tools/image_generation/dalle_image_gen.py

- Write file and image S3 fix
- Refactored s3,resource helper

S3 fix and refactoring 

---

superagi/helper/json_cleaner.py

fix #254, now support all kins of languages.

Fix json process

---

superagi/jobs/agent_executor.py

Removing web scraper from default tool.

remove web scraper from default

---

superagi/tools/email/send_email_attachment.py

* fix typo 'attachement' in tool flow logic
* unable to find reference in frontend flow to change the same, hence keeping this WIP
* needs to be tested locally on GUI for PR to complete

[WIP] partially fix typo, email attachment tool logic

---

superagi/jobs/agent_executor.py

Fix typo in agent_executor.py

---

main.py
migrations/versions/516ecc1c723d_adding_marketplace_template_id_to_agent_.py
requirements.txt
superagi/controllers/agent.py
superagi/controllers/agent_template.py
superagi/controllers/agent_workflow.py
superagi/helper/auth.py
superagi/models/agent.py
superagi/models/agent_template.py

- Downloading template from marketplace
- Using the templates while creating agents

Agent templates changes

---

gui/pages/Content/Agents/AgentTemplatesList.js
gui/pages/Content/Marketplace/Market.module.css
gui/pages/Content/Marketplace/MarketAgent.js

Css changes for agent templates and marketplace

minor css changes

---

gui/pages/Content/Marketplace/Market.module.css

fixing css on marketplace

---

gui/pages/Content/Agents/AgentCreate.js
gui/pages/Content/Marketplace/AgentTemplate.js
gui/pages/api/DashboardService.js

now the card on marketplace will send details

fixing of marketplace bug

---

README.MD

Information added:
SuperAGI Architecture
Agent Architecture
Agent Workflow Architecture
Tools Architecture
ER Diagram

Added the Architecture and ER Diagram

---

README.MD

Added a video showcasing SuperCoder creating a personal finance app.

Super coder demo video

---

superagi/models/agent_template.py
tests/unit_tests/agent/test_agent_prompt_builder.py
tests/unit_tests/agent/test_output_parser.py
tests/unit_tests/helper/test_tool_helper.py
tests/unit_tests/models/test_agent_template.py
tests/unit_tests/test_tool_manager.py

Adding unit tests for some core classes

Unit tests coverage

---

superagi/tools/searx/searx_toolkit.py
tests/unit_tests/tools/test_searx_toolkit.py

Adding toolkit for searx
Searx toolkit was not present.
Adding a toolkit for Searx containing required information.

Searx toolkit

---

main.py

Added ```@app.on_event("startup")``` for server startup tasks and also to limit the global scope of session created in main.py to the function scope as it was creating issues while writing controller level unit test while creating test client.
Issue with writing unit test for controllers because of global scope of session in main.py
- Added ```@app.on_event("startup")``` for server startup
- ```/github-login``` using middleware session instead of global.
- Works well with new build on start-up of server these tasks are executed.

Fixing main.py

---

gui/pages/Content/Marketplace/MarketAgent.js

Opening marketplace to public, adjusted template list api call
None
Made the marketplace api public for agent templates
Changes were verified in local with url containing "marketplace"

Opening marketplace to public, readjusted api call

---

gui/pages/Content/Marketplace/AgentTemplate.js
gui/pages/Content/Marketplace/Market.module.css
gui/pages/Content/Marketplace/MarketAgent.js
gui/pages/Content/Marketplace/MarketplacePublic.js

Handling some UI changes in public marketplace page. Also resolved bug for fetching template details by using exposes api. Made Minor CSS change as per design. 
Also made the SuperAGI logo clickable which will redirect to app.superagi.com or localhost depending on the user.
No related issues posted as of now
Only UI has been affected for most of the part.
Exposed api for fetching the agent template details is used
The user can navigate to marketplace.superagi.com and check if no api calls are failing
- [ yes ] Bug fix (non-breaking change which fixes an issue)
- [ yes ] New feature (non-breaking change which adds functionality)
- [ yes ] My pull request is atomic and focuses on a single change.
- [ yes ] I have read the contributing guide and my code conforms to the guidelines.
- [ yes ] …

Bugs resolved in public marketplace

---

superagi/controllers/toolkit.py
superagi/models/toolkit.py
tests/unit_tests/controllers/test_toolkit.py
tests/unit_tests/models/test_toolkit.py

Marketplace API has support for ```is_installed```
```is_installed``` was missing in marketplace API
- Added ```is_installed``` support in ```/get/list```
- Added unit test for the same.

Updated is_installed

---

main.py

Fixing ```main.py```
No related issue.
Fixed indentation for ```@app.on_event("startup")```
No error on startup

Fixed main.py indentation

---

superagi/models/toolkit.py

Update Toolkit model docs.
No related issue.
Updated docs.
NA

Dev docs fix

---

gui/pages/Content/Marketplace/AgentTemplate.js
gui/pages/Content/Marketplace/EachTool.js
gui/pages/Content/Marketplace/MarketAgent.js
gui/pages/Content/Marketplace/MarketTools.js
gui/pages/_app.css

Changing apis for public marketplace for tools and agent templates
added different api endpoints for public marketplace to fetch tools and agent templates
changes can be checked in the localhost:3000/marketplace in local

Public marketplace tools

---

.github/PULL_REQUEST_TEMPLATE.md
README.MD
gui/pages/Content/Marketplace/AgentTemplate.js
gui/pages/Content/Marketplace/MarketplacePublic.js

Resolving conflicts between main and dev
conflicts resolved in the frontend

Dev to main

---

main.py
superagi/helper/tool_helper.py

Prod Fix for toolkit registration of already existing users.
Toolkit not visible for exisiting users/organisations
Register Toolkit on startup of application for all organisations

Prod user toolkit fix

---

gui/pages/Content/Agents/AgentCreate.js
gui/pages/Dashboard/Content.js
gui/pages/Dashboard/Settings/Settings.js
gui/pages/Dashboard/TopBar.js
gui/utils/utils.js

Converted the settings popup to a tab similar to other sections in the application
None 
Used the openNewTab event to send a message to create a new tab in the Content.js file. 
Clicking on the settings button on the top bar opens a new Settings tab. Only one settings tab is allowed

Settings page fix

---

gui/Dockerfile
gui/pages/Content/Agents/AgentCreate.js
gui/pages/Content/Marketplace/AgentTemplate.js
gui/pages/Content/Marketplace/EachTool.js
gui/pages/Content/Marketplace/MarketAgent.js
gui/pages/Content/Marketplace/MarketTools.js
gui/pages/_app.css
main.py
superagi/tools/slack/send_message.py

Dev -> Main

---

superagi/tools/code/prompts/generate_logic.txt
superagi/tools/code/write_code.py
superagi/tools/code/write_test.py

1. Added fix for content issue in writespec
2. Added prompt for generate-logic for requirements.txt, package.json and run.sh file
1. Added prompt txt file and added it to main prompt of code
Run docker compose up --build and run supercoder template

Added fix for supercoder

---

docker-compose.yaml
gui/.dockerignore
gui/Dockerfile
package-lock.json

Fixing docker build issue for gui

fixing docker compose issue

---

superagi/models/toolkit.py
tests/unit_tests/models/test_toolkit.py

Updated marketplace URL
Updated marketplace URL

Updated Marketplace URL

---

superagi/jobs/agent_executor.py
superagi/tools/base_tool.py
superagi/tools/jira/create_issue.py
superagi/tools/jira/edit_issue.py
superagi/tools/jira/get_projects.py
superagi/tools/jira/search_issues.py
superagi/tools/jira/tool.py

Fixing JIRA tool issue to fetch the tool config details

fixing JIRA tool issue to fetch keys

---

superagi/controllers/toolkit.py
superagi/jobs/agent_executor.py
tests/unit_tests/jobs/test_agent_executor.py

Tools directory default fix
TOOLS_DIR not found in config.yaml
Added a default handling for tools directory

Tools dir backward compatible

---

superagi/tools/code/write_code.py
superagi/tools/email/read_email.py
superagi/tools/file/read_file.py
superagi/tools/file/write_file.py
superagi/tools/github/add_file.py
superagi/tools/github/delete_file.py
superagi/tools/image_generation/dalle_image_gen.py
superagi/tools/jira/create_issue.py
superagi/tools/jira/edit_issue.py
superagi/tools/jira/get_projects.py

updated docs 
* fix some wrong returns explanations
* improve some returns explanations

Fix comments

---

tests/unit_tests/jobs/test_agent_executor.py

Added Unit Test for Agent Executor
Added Unit Test for Agent Executor

Added Unit Test for Agent Executor

---

gui/pages/Content/Marketplace/Market.module.css
gui/pages/Content/Marketplace/MarketplacePublic.js

Made minor changes to marketplace
None 
Changed the pointer events to None for marketplace text, try for free today text changed to sign up in primary button in public marketplace
Cursor over marketplace shows it is not editable, try for free button text has changed

Minor Frontend Bug fixes

---

superagi/controllers/tool_config.py
superagi/models/toolkit.py
tests/unit_tests/models/test_toolkit.py

Fixed update tool config keys with organisation
Config update query not associated with organisation
Corrected the query

bug fixed for update keys

---

superagi/tools/email/send_email.py
superagi/tools/email/send_email_attachment.py
tests/unit_tests/tools/email/test_send_email_attachment.py

Fix for read file email

---

gui/pages/Content/Agents/Details.js
gui/pages/Content/Toolkits/ToolkitWorkspace.js
gui/pages/Dashboard/Content.js

-Toolkit data stored in localstorage for persistence when switching between tabs
-Agent details tool click opens tools included section of toolkit in a new tab
None
-Used localstorage to solve first issue, storing current tab state and api config keys for toolkits using a localstorage key based on unique internal id similar to new agent tab
-Used eventBus to solve second issue
-Tested by opening 2 tabs, one is a toolkit where information is filled. switched between different tabs and came back to the toolkit, the input data is persisting.
-Clicked on a tool in the details part of the agent, a new tab opens up wrt the related toolkit of the tool clicked.

Frontend bugs

---

gui/pages/Content/Marketplace/EachTool.js
gui/pages/Content/Marketplace/MarketAgent.js
gui/pages/Content/Marketplace/MarketTools.js
gui/pages/Content/Toolkits/AddTool.js
gui/pages/Content/Toolkits/AddToolkit.js
gui/pages/Content/Toolkits/Toolkits.js
gui/pages/Dashboard/Content.js
gui/pages/api/DashboardService.js

Add tool using github repo link
None
Add tool from toolkit list opens a new tab where user can enter github repo link
Go to toolkits, click on Add tool, enter github repo url and click on add tool. A toast appears with the following message: 'Tool will be installed in a while'.

Add Toolkit Local Frontend

---

gui/pages/Content/Toolkits/ToolkitWorkspace.js
gui/pages/_app.js

Twitter tool was not working because local storage was not getting set properly. I have fixed the related issue.
Twitter Tool bug
I have handled the localstorage for twitter_toolkit_id correctly.

Twitter frontend bug fix

---

gui/pages/Content/Agents/ActivityFeed.js
gui/pages/Content/Agents/AgentWorkspace.js
gui/pages/Content/Agents/Details.js
gui/pages/api/DashboardService.js

Frontend for setting goals and instructions in execution/run level
In new run creation goals and instructions were not getting updated
Removed goals and instructions from agent level, and moved to execution level. Created a new api and integrated it which helps in fetching the goals & instructions per run and displaying it in details. 
Clicking on different runs in run history updated the goals and instructions wrt that particular selected run. When a new run is created it picks up the newly assigned goals and instructions and displays them in the details

Execution bug frontend

---

gui/pages/Content/Agents/AgentCreate.js
gui/pages/_app.js

Access token should persist in localstorage
Web app having issue, reloading would remove accesstoken, user would need to signup again
created a list of excluded keys that persist even after local storage is cleared. added access token to that excluded key list
set env to prod, remove all localstorage, try running the app, once logged in refresh the browser tab, shouldn't ask you to login again.

Access Token Issue

---

superagi/jobs/agent_executor.py
superagi/resource_manager/resource_summary.py

Wait till all resource have a summary

Wait till all resource have a summary 

---

gui/pages/Content/Agents/AgentCreate.js
gui/pages/Content/Agents/Details.js
gui/pages/Content/Agents/ResourceManager.js
gui/pages/_app.css

-Resolved empty instruction bug in agent details
-Removed LTM dB selection from agent creation form
-Refactored the supported file format text in file upload input
None 
-used Js filter to filter out empty instructions
-commented out the LTM dB checkbox and selection dropdown
-updated the text and improved padding
Changes are visible directly in frontend

frontend bug fixes

---

superagi/resource_manager/resource_summary.py

moved condition

---

gui/pages/Content/Marketplace/AgentTemplate.js
gui/pages/Content/Marketplace/EachTool.js
gui/pages/Content/Marketplace/Market.js
gui/pages/_app.js

Installing agent templates and toolkits from public marketplace
Clicking on sign in to install was redirecting to main app but not installing the template
used localstorage to store the agent template id and/or toolkit template name when clicked on sign in to install, fetching the same when the app starts and installing their respective template
went to localhost:3000/marketplace and tried installing agent template and toolkit, it is correctly displaying in the main app

Marketplace Install Bug Fix

---

gui/pages/Content/Marketplace/EachTool.js
gui/pages/Content/Toolkits/ToolkitWorkspace.js
gui/pages/Content/Toolkits/Toolkits.js
gui/utils/utils.js
superagi/tools/webscaper/web_scraper_toolkit.py

Centralised the toolkit icon applier
None 
Optimized the icon supplier for toolkits which existed in 3 files and moved it to utils.js
Made the changes and tested the fix, everything works as expected

Centralise Toolkit Icons

---

gui/pages/Content/Agents/AgentCreate.js
gui/pages/Content/Agents/ResourceList.js
gui/pages/Content/Agents/ResourceManager.js
gui/pages/Dashboard/Content.js
gui/utils/utils.js

Fixed a bug related to resource manager fetching files continuously
None
Moved the html logic for resource item into a different file and integrated the component in the main html part. removed multiple returns for other html
Uploaded and outputed files by running agents, works correctly

Resources Frontend Bug

---

gui/utils/utils.js
superagi/tools/webscaper/web_scraper_toolkit.py

reverted web scrapper toolkit name change
Web scrapper toolkit not showing up in list of tools selected in agent details
renamed web scraper to web scrapper
Tested with agent create and selected web scrapper toolkit, showing up in details

Reverted web scrapper change

---

gui/pages/Content/Toolkits/ToolkitWorkspace.js
gui/pages/Content/Toolkits/Toolkits.js

Centralised toolkit authentication in frontend by name
None
Multiple authenticate buttons were being used for different toolkits, centralised it into one and conditionally made api calls
Checked the console.log for both google and twitter, returns the correct result

Refactor authenticate button

---

gui/pages/Content/Marketplace/MarketTools.js
gui/pages/Dashboard/Content.js
superagi/agent/super_agi.py
superagi/controllers/agent_execution_feed.py

Removed the date time being sent to frontend in the agent activity feed section 
Made a minor placeholder change on frontend
No issue related
The appending of the date and time in the agent execution is stopped. 
Minor change

Date removed

---

superagi/jobs/agent_executor.py

solution for summary not getting replaced

name change because of query resource

---

config_template.yaml

…hey don't accidentally copy the whole config_template.yaml and don't set these properly
By default comment out keys which are not needed by default so that they don't accidentally copy the whole config_template.yaml and don't set these properly

by default comment out keys which are not needed 

---

superagi/helper/tool_helper.py
superagi/worker.py
tests/unit_tests/helper/test_tool_helper.py
tools.json

Imports handling for external tools
Fixing module not found error.
Added import to system paths.

External tool fix

---

superagi/controllers/agent_execution_config.py
tests/unit_tests/controllers/test_agent_execution_config.py

Backward fix and fix for schedule agent where execution is created later and so if agent execution config is None details will be fetched from Agent Config.
Backward Compatible fix with Schedule Agent.
Fetching Agent Execution Config from Agent Config in case execution is not created. 
When execution is not present agent config will be sent like instructions and goals from agent config will be fetched in case there is no agent config.

Agent execution config fix

---

superagi/agent/agent_prompt_builder.py
superagi/agent/output_parser.py
superagi/agent/prompts/create_tasks.txt
superagi/helper/feed_parser.py
superagi/helper/json_cleaner.py
superagi/image_llms/base_image_llm.py
superagi/image_llms/openai_dalle.py
superagi/llms/base_llm.py
superagi/llms/openai.py
superagi/resource_manager/file_manager.py
superagi/tools/email/send_email.py
superagi/tools/email/send_email_attachment.py
superagi/tools/image_generation/dalle_image_gen.py
superagi/tools/resource/query_resource.py
superagi/vector_store/chromadb.py
superagi/vector_store/embedding/base.py
superagi/vector_store/embedding/openai.py
superagi/vector_store/pinecone.py
tests/unit_tests/agent/test_agent_prompt_builder.py
tests/unit_tests/tools/image_generation/test_dalle_image_gen.py
tests/unit_tests/vector_store/test_chromadb.py

Cleaning up LLM model classes and refactoring

Llm cleanup

---

main.py

minor fix to avoid toolkit initiation in prod

---

superagi/helper/auth.py

Fixed oauth bug in get organisation
Oauth bug in get organisation
Fixed oauth bug in get organisation

fixed oauth get org

---

main.py

main -> dev

---

gui/pages/Content/Agents/AgentCreate.js
superagi/controllers/agent.py
superagi/controllers/types/agent_with_config.py
superagi/models/agent.py
superagi/models/agent_template.py

Removed rolling window from frontend
Removed rolling window frontend
Removed rolling window frontend
Removed rolling window frontend

Remove rolling window

---

superagi/controllers/toolkit.py

Date format fix in marketplace.
Date format fix in marketplace.
Date format issue in marketplace.

Updated Date Format

---

gui/pages/Content/Marketplace/AgentTemplate.js
gui/pages/Content/Marketplace/EachTool.js
gui/pages/Content/Marketplace/Market.js
gui/pages/Content/Marketplace/MarketAgent.js
gui/pages/Content/Marketplace/MarketTools.js
gui/pages/Content/Marketplace/MarketplacePublic.js

Resolved unusual loading appearance in agent template. Made minor fixes to loading
No Issues
Loading has been added in agent template and minor bug fixed in toolkit marketplace page
Frontend changes made and showed to product

Marketplace bug2

---

superagi/helper/resource_helper.py
tests/unit_tests/helper/test_resource_helper.py

Fixed path for local files
Local file not found the issue.
Separately handled path for S3 and File
Local File storage download feature should work.

Resource manager path fix

---

superagi/vector_store/qdrant.py

Minor change

---

gui/pages/Content/Agents/ResourceList.js
gui/utils/utils.js

File names are now downloaded with run name and time stamp
Run dropdown timer removed

ui changes

---

tests/unit_tests/controllers/test_agent_execution_config.py

comment out test so others can push to dev

fixing test

---

superagi/jobs/agent_executor.py

Removing exception handling to solve max-iteration issue
Removing exception handling to solve max-iteration issue
Removing exception handling to solve max-iteration issue

Max iteration fix

---

superagi/helper/resource_helper.py
superagi/tools/base_tool.py

Minor bug fixes

---

gui/pages/Dashboard/Content.js

Very minor fix

---

gui/pages/Content/Agents/AgentCreate.js
gui/pages/Content/Agents/AgentWorkspace.js
main.py
superagi/agent/output_parser.py
superagi/controllers/agent.py
superagi/models/agent.py

Renaming fixed task queue

---

gui/pages/Content/APM/ApmDashboard.js
gui/pages/Content/Agents/AgentSchedule.js
gui/pages/Dashboard/Content.js
gui/pages/Dashboard/Dashboard.module.css
gui/pages/_app.css

Bug fixes revamp

---

superagi/jobs/scheduling_executor.py

apm scheduling addition

---

tests/unit_tests/helper/test_feed_parser.py

Unit test fix
Unit test fix
Unit test fix
Unit test fix

Updated Test

---

superagi/tools/email/README.md
superagi/tools/twitter/README.md

Twitter Readme and Email Readme Clean Up

---

gui/pages/Content/Agents/AgentWorkspace.js

Changed delete label to delete run to delete a certain execution of an agent

delete run label

---

gui/pages/Content/Toolkits/ToolkitWorkspace.js
gui/pages/Dashboard/Content.js
superagi/controllers/google_oauth.py
superagi/controllers/twitter_oauth.py
superagi/helper/twitter_tokens.py

Twitter and Google Oauth for Web

---

superagi/models/db.py

Updated DB pool and other settings
QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30.00 (Background on this error at: https://sqlalche.me/e/20/3o7r)

Updated DB settings

---

superagi/resource_manager/file_manager.py

csv file fix

---

gui/pages/Content/Agents/ActivityFeed.js
gui/pages/Content/Agents/AgentCreate.js
gui/pages/Content/Agents/AgentSchedule.js
gui/pages/Content/Agents/AgentTemplatesList.js
gui/pages/Content/Agents/AgentWorkspace.js
gui/pages/Content/Agents/Agents.js
gui/pages/Content/Agents/Details.js
gui/pages/Dashboard/Content.js
gui/pages/Dashboard/Settings/Settings.js
gui/pages/_app.css
gui/utils/utils.js

Bugs fixes new

---

superagi/resource_manager/resource_summary.py

fixed add_to_vector_store_and_create_summary

fixed add_to_vector_store_and_create_summary

---

superagi/agent/super_agi.py

fixing  AttributeError in superagi.worker # execute_agent

fix 97971622

---

gui/pages/Content/Agents/AgentCreate.js
gui/pages/api/DashboardService.js
superagi/controllers/google_oauth.py
superagi/controllers/organisation.py
superagi/helper/twitter_tokens.py
superagi/llms/google_palm.py
superagi/llms/openai.py

Fixes models issue. People were trying to run agents with LLMs to which their access key didn't have access.

Llm models fix

---

gui/pages/Content/Agents/AgentCreate.js
gui/pages/Content/Marketplace/MarketTools.js
gui/pages/Content/Toolkits/Toolkits.js
gui/utils/utils.js

Removed unnecessary toolkits from marketplace

Removed unnecessary toolkits from marketplace

---

gui/pages/Content/APM/ApmDashboard.js
gui/pages/Content/Agents/ResourceManager.js
gui/pages/_app.css
gui/utils/utils.js
superagi/apm/tools_handler.py

ui bug bash fixes

---

main.py

Changed jwt expiry to 200 hours instead

JWT Expiry Issue fixed

---

main.py

Login issue fix

---

main.py

Login issue fixx

---

superagi/llms/llm_model_factory.py

Google Palm fixx

---

gui/package-lock.json
gui/package.json
gui/pages/Content/Agents/ActivityFeed.js
gui/pages/Content/Agents/AgentCreate.js
gui/pages/Content/Agents/AgentWorkspace.js
gui/pages/_app.css

Bug Fixes::
1. Scheduled Agent Bug Dev Ready (QA needed to confirm it)
2. APM Bug issue
3. Create Agent Tools Dropdown issue fixed

ui bug fixes

---

superagi/tools/image_generation/stable_diffusion_image_gen.py
superagi/tools/instagram_tool/README.MD
tests/unit_tests/tools/image_generation/test_stable_diffusion_image_gen.py

Instagram tool added to toolkit. Now agents will be able to post photos generated by stable diffusion along with a relevant caption directly to user's instagram business accounts
Added pytests for the code

handled resource path change

---

main.py

Backward compatibility by default time of 200 hrs.
Internal server error due to no JWT_EXPIRY present in config.yaml
Checking if JWT_EXPIRY is none setting it to default time.

Jwt expiry backward fix

---

superagi/helper/tool_helper.py

Toolkit Marketplace Readme fix

Toolkit Marketplace Readme fix

---

.gitignore

Adding tools.json to .gitignore

Adding tools.json

---

gui/pages/Content/Marketplace/AgentTemplate.js
superagi/controllers/agent.py
superagi/jobs/scheduling_executor.py

Bug fixes afternoon

---

superagi/controllers/knowledges.py

very minor fix for naming

---

main.py
superagi/agent/agent_prompt_builder.py
superagi/agent/prompts/tool_selection.txt
superagi/tools/code/prompts/write_code.txt
superagi/tools/code/prompts/write_test.txt

Tool selection prompt fix
Tool selection not working properly.
Tool selection prompt fix

Updated prompt for tool selection 

---

superagi/tools/image_generation/dalle_image_gen.py
tests/unit_tests/tools/image_generation/test_dalle_image_gen.py

args fix in dalle

---

gui/pages/Content/Knowledge/Knowledge.js
gui/pages/Content/Knowledge/KnowledgeDetails.js

minor changes

---

gui/pages/Content/Agents/AgentWorkspace.js
gui/pages/Content/Knowledge/KnowledgeForm.js
gui/pages/Content/Marketplace/KnowledgeTemplate.js

The user will now not be able to select knowledges which are striked off

Minor changes launch

---

gui/pages/Content/Agents/Details.js
superagi/controllers/agent.py

Fix for agent details - not fetching data

---

gui/pages/Dashboard/Content.js
gui/pages/Dashboard/Dashboard.module.css

Knowledge List Fix

---

superagi/controllers/knowledges.py

Offset fix

---

superagi/controllers/knowledges.py

Naming changes

---

superagi/models/agent_template.py

Save Agent Template Fix
None was not handled while calling agent template configs
A check was added to verify first if the config value is None, if not execution happens

Save Agent Template Fix

---

gui/pages/Content/Knowledge/AddKnowledge.js
gui/pages/Content/Knowledge/KnowledgeDetails.js
gui/pages/Content/Knowledge/KnowledgeForm.js
gui/pages/Content/Marketplace/KnowledgeTemplate.js
gui/pages/Content/Marketplace/Market.js
gui/pages/Dashboard/Content.js
superagi/tools/file/read_file.py

Knowledge bug fixes:
-added add vector db button on install template dropdown and add knowledge index selection dropdown.
-overview text change in knowledge template
-disabled indexes cant be selected in install template and add knowledge

Knowledge fixes

---

gui/pages/Dashboard/SideBar.js
gui/pages/Dashboard/TopBar.js

Product Hunt Changes

---

docker-compose.yaml
superagi/resource_manager/resource_summary.py
superagi/tools/resource/query_resource.py
superagi/worker.py

temp change to query resource so we can use query resource without creating summary
same as #904
The summary is replaced with file names

Fix resource query dev

---

gui/pages/Content/Marketplace/MarketKnowledge.js
superagi/helper/github_helper.py
superagi/helper/s3_helper.py
superagi/helper/twitter_helper.py
superagi/tools/email/send_email_attachment.py
superagi/tools/file/delete_file.py
superagi/tools/github/add_file.py
superagi/tools/github/search_repo.py
tests/unit_tests/helper/test_github_helper.py
tests/unit_tests/helper/test_s3_helper.py
tests/unit_tests/tools/github/test_add_file.py

Resource manager s3 fix

---

gui/pages/Content/Toolkits/ToolkitWorkspace.js
superagi/controllers/google_oauth.py

Fix for google calendar oauth

---

superagi/tools/image_generation/dalle_image_gen.py
tests/unit_tests/tools/image_generation/test_dalle_image_gen.py

Dalle openai fix dev

---

superagi/tools/image_generation/dalle_image_gen.py
tests/unit_tests/tools/image_generation/test_dalle_image_gen.py

Dalle openai fix

---

gui/pages/Content/Toolkits/Tool.module.css
gui/pages/Content/Toolkits/ToolkitWorkspace.js
gui/pages/_app.css
superagi/controllers/tool_config.py

Certain fields in toolkits have been masked and check for all the required fields has been added.
no related issues
Frontend checks have been added

masking of certain fields in toolkits complete

---

docker-compose.yaml

revert docker compose

---

superagi/tools/image_generation/stable_diffusion_image_gen.py

Changes in stable diffusion

---

superagi/tools/image_generation/stable_diffusion_image_gen.py

stable diffusion changes

---

gui/pages/Dashboard/Settings/Model.js

Settings bug fix, minor frontend change
no issues related

settings bug fix

---

gui/pages/Content/APM/ApmDashboard.js
gui/pages/Content/Agents/Details.js
gui/pages/Dashboard/Content.js
gui/pages/Dashboard/TopBar.js
gui/pages/_app.css

Dev Frontend Bug Fixes

---

gui/pages/Content/Toolkits/ToolkitWorkspace.js

Update and Authenticate button fix

---

gui/pages/Content/APM/ApmDashboard.js
gui/pages/Content/Agents/Details.js
gui/pages/Dashboard/Content.js
gui/pages/Dashboard/TopBar.js
gui/pages/_app.css

Main Frontend Bug Fixes

---

gui/pages/_app.js
gui/pages/api/DashboardService.js
main.py

Due to nextjs build process which hard-codes all the environment variables into the build files
it becomes impossible for users to change the env variables.
this causes dockerimages won't be able to work with github oauth if users wants to set it up themself
Instead of getting github client id from env 
now an api is instead used

Fix for gui docker image to work with github client id

---

gui/pages/Content/Marketplace/KnowledgeTemplate.js

Knowledge bug

---

gui/pages/Content/APM/ApmDashboard.js

Main Bug Fixes

---

gui/pages/Content/Marketplace/KnowledgeTemplate.js

knowledge bug resolved

---

gui/pages/Content/Marketplace/KnowledgeTemplate.js

minor bug resolved

---

.github/workflows/ci.yml

fix skipping test when they originate from forks

workflow test

---

gui/pages/Content/Toolkits/Tool.module.css
superagi/controllers/tool_config.py
tools.json

json text area functionality for google analytics

---

superagi/controllers/agent_execution.py

New run fix

---

superagi/controllers/agent_execution.py
superagi/models/agent_execution_config.py

Edit agent fix

---

superagi/tools/duck_duck_go/duck_duck_go_search.py

fix typo in duck_duck_go_search.py

---

superagi/worker.py

chaning default redis url to point to super__redis
some users forgot to keep the redis url in config
So if there is no redis url in config we set a default one

setting default redis url

---

superagi/controllers/agent_execution_config.py
superagi/models/agent_execution_config.py

Schedule agent fix

---

gui/pages/Content/Agents/AgentCreate.js

Bug fixes deployment 10

---

gui/pages/Content/Toolkits/ToolkitWorkspace.js
superagi/controllers/google_oauth.py

Google calendar oauth

---

superagi/models/agent_config.py
tests/unit_tests/controllers/test_update_agent_config_table.py

Schedule fix

---

superagi/controllers/agent_execution.py

fix: added condition to check for empty arrays from getting converted to int

add small check

---

gui/pages/Content/Agents/ActivityFeed.js
gui/pages/Content/Agents/AgentCreate.js
gui/pages/Content/Agents/AgentSchedule.js
gui/pages/Content/Agents/AgentWorkspace.js
gui/pages/Content/Agents/Details.js

detail bug in schedule agent and naming of new run in edit agent

detail bug in schedule agent and naming of new run in edit agent

---

superagi/agent/tool_builder.py

Bug Fix for external and marketplace tool

External tools, marketplace tools fix

---

docker-compose-dev.yaml
gui/pages/Content/Agents/AgentCreate.js
gui/pages/Dashboard/Settings/AddDatabase.js
gui/pages/Dashboard/TopBar.js
gui/pages/_app.css

bug fixes of weaviate and profile dropdown bug

bug fixes of weaviate and profile dropdown bug

---

superagi/agent/tool_builder.py
tests/unit_tests/agent/test_tool_builder.py

Fix for unit tests for tool_builder.py file.

Test tool builder fix

---

superagi/controllers/api/agent.py
superagi/worker.py

fixed api_bug

---

README.MD

Added 
- docs
- video
- new contributors

Added docs, video, new contributors

---

superagi/agent/tool_builder.py

partial revert 1105

---

superagi/tools/email/send_email.py
superagi/tools/email/send_email_attachment.py

Changes for no receiver address

---

superagi/controllers/toolkit.py
tests/unit_tests/controllers/test_toolkit.py

Add entrypoint

---

gui/pages/Content/Agents/ActivityFeed.js
superagi/jobs/agent_executor.py

Reducing delays
Reducing delays

Delay change

---

Dockerfile

added expose 8001

---

superagi/helper/github_helper.py

made changes to github helper

---

superagi/tools/email/send_email.py

\n bug resolved

---

Dockerfile

add expose 8001 in backend dockerfile

Expose docker port dev

---

requirements.txt

Macs where not working because of this
https://github.com/huggingface/safetensors/issues/346

Safetensors fix dev 

---

superagi/tools/jira/edit_issue.py
superagi/tools/jira/search_issues.py
tests/unit_tests/tools/jira/test_edit_issue.py
tests/unit_tests/tools/jira/test_search_issues.py

Jira Bug Fix

---

superagi/tools/image_generation/dalle_image_gen.py
superagi/tools/image_generation/image_generation_toolkit.py

added tool config for dalle

---

superagi/jobs/agent_executor.py

Stop agent if model doesnt exsist
If model does exsist it throws an exception
we use this exception to stop

stop agent from executing if model is not found

---

tools.json

revert tools.json

---

superagi/tools/tool_response_query_manager.py

add null check

---

README.MD

- Added new contributors
- Updated steps for running SuperAGI
- Added New Features
- Added API documentation link

Updated README with new features, contributors, and API docs

---

config_template.yaml
main.py
migrations/env.py
superagi/models/db.py

Remove hardcoded creds so that docker image users can change db_host names etc

Remove hardcoded creds

---

superagi/controllers/agent_execution.py

Fix for new run and edit agent

fix for new run and edit agent

---

superagi/tools/knowledge_search/knowledge_search.py
superagi/tools/knowledge_search/knowledge_search_toolkit.py

Knowledge search fix

---

superagi/tools/knowledge_search/knowledge_search.py
superagi/tools/knowledge_search/knowledge_search_toolkit.py

fix for knowledge search tool

---

superagi/apm/call_log_helper.py

Fixes for call logs for the model feature

call logs bugs main

---

docker-compose.yaml
superagi/apm/call_log_helper.py

Models calls logs dev

---

superagi/controllers/models_controller.py
superagi/models/models.py

marketplace changes

---

gui/pages/Content/Agents/Agents.module.css
gui/pages/Content/Models/ModelDetails.js
gui/pages/Content/Models/ModelInfo.js
gui/pages/Content/Models/ModelMetrics.js
gui/pages/Content/Toolkits/ToolkitWorkspace.js
gui/pages/_app.css

models scroll fix, format of log timestamp fix, adding of loader to models, toolkit metrics dropdown bug fixed, publish agent dropdown bug

bugs fixes

---

superagi/controllers/models_controller.py
tests/unit_tests/controllers/test_models_controller.py

Unit Test Fix

---

gui/pages/Content/Marketplace/KnowledgeTemplate.js

fix added for index state

---

README.MD

added button

---

gui/pages/Content/Models/MarketModels.js
superagi/controllers/models_controller.py
tests/unit_tests/controllers/test_models_controller.py

The issue where the models where not visible on marketplace.superagi.com has been  resolved.

Models marketplace changes

---

gui/pages/Content/Models/MarketModels.js
superagi/controllers/models_controller.py
superagi/models/models.py

models changes

---

superagi/controllers/api_key.py

Sdk minor changes

---

gui/pages/Content/Models/MarketModels.js
gui/pages/Content/Models/ModelTemplate.js
superagi/controllers/models_controller.py
superagi/controllers/types/models_types.py
superagi/models/models.py

1. Added Models Type Enum file.
2. Added content for Marketplace and edited the css.
3. Previously Installed state is changed back to Install state

Models marketplace updates

---

superagi/worker.py

Made a simple change to worker.py file

worker.py updates

---

gui/pages/Content/Agents/AgentWorkspace.js

removing single qoutes

---

gui/package-lock.json
gui/package.json
gui/pages/Content/APM/ApmDashboard.js
gui/pages/Content/Toolkits/Metrics.js
gui/pages/_app.css
superagi/agent/tool_executor.py
superagi/apm/tools_handler.py
tests/unit_tests/apm/test_tools_handler.py

1. Tooltip is fixed
2. Logo for the same tool sometime shows and sometimes it doesn't and name of tool is fixed
3. Sort most used tools based on the Calls
4. Most Used Tools issue is resolved too

apm changes

---

README.MD

1. Updated the architecture for:
- SuperAGI Architecture
- Agent Workflow
- Tools Workflow
- ER Diagram
2. Added new Contributors

Updated Architecture

---

gui/pages/Content/APM/ApmDashboard.js
gui/pages/Content/Marketplace/Market.js
gui/pages/Dashboard/SideBar.js

frontend changes

---

superagi/helper/validate_csv.py
superagi/tools/file/read_file.py

The “Error tokenizing data” message usually indicates that there is an issue with how the data is formatted in the CSV file. This can be due to a number of reasons, such as:
There are missing values in the CSV file that are not properly represented.
The delimiter used in the file is not consistent throughout the file.
There are unbalanced quotes in the CSV file.
There are special characters in the CSV file that are not properly encoded.

read tool fix

---

superagi/helper/feed_parser.py
tests/unit_tests/helper/test_feed_parser.py

Fixing error handling in feed parser

error_handling fix

---

superagi/controllers/models_controller.py
superagi/models/models.py

Models Marketplace Issue resolved for main

Models Marketplace bug fix for main

---

superagi/agent/agent_message_builder.py

Fix 1257 dev

---

superagi/controllers/models_controller.py
superagi/models/models.py

Models Marketplace bug fix for add_entrypoint

---

superagi/controllers/api/agent.py

save other config to agent_execution config

---

superagi/controllers/api/agent.py

Fix api dev

---

superagi/agent/agent_iteration_step_handler.py
superagi/agent/agent_message_builder.py
superagi/agent/agent_tool_step_handler.py
superagi/agent/queue_step_handler.py
superagi/helper/error_handler.py
superagi/tools/code/improve_code.py
superagi/tools/code/write_code.py
superagi/tools/code/write_spec.py
superagi/tools/code/write_test.py
superagi/tools/duck_duck_go/duck_duck_go_search.py
superagi/tools/github/review_pull_request.py
superagi/tools/google_search/google_search.py
superagi/tools/google_serp_search/google_serp_search.py
superagi/tools/instagram_tool/instagram.py
superagi/tools/searx/searx.py
superagi/tools/thinking/tools.py
tests/unit_tests/helper/test_error_handling.py

rename error_handling.py to error_handler.py

rename error_handling.py to error_handler.py

---

gui/pages/_app.js
gui/pages/api/apiConfig.js
gui/utils/utils.js

Analytics login

---

gui/pages/_app.js
gui/pages/api/apiConfig.js
gui/utils/utils.js

google analytics login for main

---

superagi/tools/google_calendar/delete_calendar_event.py
superagi/tools/google_calendar/event_details_calendar.py

calendar issues fixed

---

superagi/tools/google_calendar/delete_calendar_event.py
superagi/tools/google_calendar/event_details_calendar.py

calendar bug fixed

---

superagi/tools/file/append_file.py

append fle tool bug fixed

---

superagi/tools/file/append_file.py

append file tool fixed

---

gui/package-lock.json
gui/package.json
gui/pages/Dashboard/TopBar.js
gui/pages/_app.js

adding cookie in access token

---

superagi/agent/workflow_seed.py

Fixing the existing recruitment workflow.
Fixing the existing recruitment workflow.

Fix Recruitment Workflow

---

gui/pages/Content/Models/ModelForm.js
gui/pages/Content/Models/Models.js

Runtime error in models resolved

models error fixed

---

gui/pages/_app.js

login for models superagi

---

gui/pages/_app.js

cookie changes

---

gui/pages/Dashboard/TopBar.js
gui/pages/_app.js
gui/pages/api/apiConfig.js
gui/utils/utils.js

Removing local storage of access token and using cookies instead

logout bug complete

---

superagi/apm/call_log_helper.py

the types where wrong so the query was failing and also the comparison was done between the id and name which was also changed

get toolkit_id and compare name instead of id

---

gui/pages/Content/Marketplace/MarketplacePublic.js

redirection for models

---

gui/pages/Content/Models/MarketModels.js
gui/pages/_app.css

marketplace flicker

---

gui/pages/Content/Agents/AgentCreate.js
gui/pages/Dashboard/TopBar.js
gui/pages/_app.js
gui/pages/api/apiConfig.js

Mixpanel additons

---

superagi/helper/encyption_helper.py

use get_config

---

.github/workflows/ci.yml

add a dummy key in encryption key

---

.github/workflows/ci.yml

Fix tests dev

---

config_template.yaml
superagi/helper/encyption_helper.py

fix for #1373

---

config_template.yaml

fixed spelling error in config_template.yaml
spelling mistake
spelling mistake
spelling mistake
spell check

Update config_template.yaml fixed spelling error

---

Dockerfile

Some users were having trouble in the download step.

change the way nltk downloads

---

superagi/helper/encyption_helper.py

minor fixes 

---

superagi/models/models_config.py

fixes for settings error

---

README.MD

Fixed Discord Link in 
"Join our [Discord community] for support and discussions"  in README.MD

Fixed Discord Link README.MD
